### ISSUE TITLE
Not able to type into the inputs.

### ISSUE THREAD

**Issue by iheartkode** [Chris911/Ask-Stack-Atom#17]
I'm on Ubuntu 14.04 Using the Latest Stable Version of Atom. 
It won't let me type at all.

No errors at all though.

**Comment by backerman** [comment]
Same thing on OS X 10.10.2; the deprecation cop is complaining about `atom.workspaceView`.

**Comment by mfathy00** [comment]
Same here i am using Ubuntu 14.04, when i try to add text in input box of ask stack nothing appear

**Comment by Chris911** [comment]
I'm currently on vacation without access to a computer. I'll take a look in a few weeks. Sorry for the delay.

**Comment by iheartkode** [comment]
Take your time, thanks for the response.

**Comment by Chris911** [comment]
Fixed. Please install v1.1.0.

**Comment by iheartkode** [comment]
Awesome

**Comment by Chris911** [comment]
Only tested on OS X but hopefully it works on Ubuntu as well. Let me know if it's not the case.
