### ISSUE TITLE
Object.add is deprecated.

### ISSUE THREAD

**Issue by Nchudson95** [Chris911/Ask-Stack-Atom#26]
Are you trying to listen for the 'core:confirm' Atom command with `jQuery::on`?
`jQuery::trigger` can no longer be used to listen for Atom commands. Please
use `atom.commands.add` instead. See the docs at
https://atom.io/docs/api/latest/CommandRegistry

**Comment by Chris911** [comment]
All deprecation warnings have been fixed in v2.0.0.
